applicaton.name=FakeStoreApi

spring.profiles.active=dev

spring.datasource.url=jdbc:postgresql://${DB_ENDPOINT}/${DB_NAME}?serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=${DEV_MODE:false}
spring.jpa.properties.hibernate.format_sql=${DEV_MODE:false}


